const TIMELINE_DATA = {
  config: {
    startYear: 1,
    endYear: 1240,
    currentYear: 1237,
    vault: "Endmyre",
    cardSurfaceOpacity: 0.78,
    textures: {
      page: "textures/endmyre_map_bg.jpg",
      card: "",
      events: "textures/endmyre_bar_bg.jpg",
      characters: "textures/character_bar_bg.jpg",
    },
  },
  tints: {
    lore: {
      tint: "rgba(225,215,195,0.78)",
      accent: "#9a7848",
      text: "#3a2e1e",
    },
    war: {
      tint: "rgba(205,178,162,0.78)",
      accent: "#8a4830",
      text: "#3a1a0e",
    },
    intrigue: {
      tint: "rgba(136, 150, 207,0.78)",
      accent: "#8896cf",
      text: "#2e2040",
    },
    civic: {
      tint: "rgba(198,208,192,0.78)",
      accent: "#5a6848",
      text: "#202818",
    },
    political: {
      tint: "rgba(218,208,175,0.78)",
      accent: "#807040",
      text: "#302810",
    },
    noble: {
      tint: "rgba(205,192,222,0.78)",
      accent: "#68509a",
      text: "#2a1e48",
    },
    faculty: {
      tint: "rgba(215,208,188,0.78)",
      accent: "#7a6838",
      text: "#302a18",
    },
    student: {
      tint: "rgba(188,210,200,0.78)",
      accent: "#4a6858",
      text: "#182820",
    },
  },
  sections: [
    {
      id: "events",
      label: "Events",
      items: [
        {
          type: "point",
          year: 1237,
          label: "Fates Vale Campaign",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          label: "Velis Arcanum Campaign",
          tint: "lore",
          obs: "Events/NewEvent",
          start: 1202,
          end: 1205,
        },
        {
          type: "span",
          start: 1122,
          end: 1133,
          label: "For The Priestess Story",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          year: 1133,
          label: "Greywood Burns, High Priestess Eira Killed",
          tint: "war",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          year: 1122,
          label: "Reave Assigned To Eira",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          year: 997,
          label: "First Liraethis Settlers, Aurelios Founded",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          year: 1116,
          label: "Reave's Parents Die",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1116,
          end: 1122,
          label: "Reave Goes Into Church Foster Care",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1125,
          end: 1237,
          label: "Onyx Covenant Established",
          tint: "intrigue",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1131,
          end: 1237,
          label: "Sanctum Establish",
          tint: "intrigue",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          label: "Spire Of The Crow Construction",
          tint: "lore",
          obs: "Events/NewEvent",
          start: 1127,
          end: 1139,
        },
        {
          type: "span",
          start: 1131,
          end: 1140,
          label: "Spire Of The Everlight Construction",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1104,
          end: 1118,
          label: "War Of Dual Horns",
          tint: "war",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1112,
          end: 1116,
          label: "Invasion Of West Endmyre",
          tint: "war",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1121,
          end: 1237,
          label: "Fates Vale Guild Established",
          tint: "intrigue",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1152,
          end: 1237,
          label: "The Gearwrights Established",
          tint: "intrigue",
          obs: "Events/NewEvent",
        },
      ],
    },
    {
      id: "characters",
      label: "Characters",
      items: [
        {
          type: "point",
          year: 1108,
          label: "Eira Aigner Born",
          tint: "student",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          year: 1108,
          label: "Reave Gales Born",
          tint: "student",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          year: 1185,
          label: "Alfius Barleyford Born",
          tint: "student",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          year: 1202,
          label: "Maret Aigner Death",
          tint: "war",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          label: "Iraelya Yesvyre Born",
          tint: "student",
          obs: "Events/NewEvent",
          year: 1097,
        },
        {
          type: "span",
          start: 1198,
          end: 1209,
          label: "Ivara Quenith Becomes Head Magister Of The Sanctum",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1209,
          end: 1237,
          label: "Vel'escan Run'talil Becomes Head Magister Of The Sanctum",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1130,
          end: 1199,
          label: "Wizard Serafin Becomes Head Of Onyx Covenant",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1199,
          end: 1212,
          label: "Iraelya Yesvyre Becomes Head Of Onyx Covenant",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          year: 1116,
          label: "Paladin Hildebad Elm Defends Leistung",
          tint: "lore",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1128,
          end: 1141,
          label: "Reginald Thelonious Worthington III Career",
          tint: "student",
          obs: "Events/NewEvent",
        },
        {
          type: "point",
          year: 1141,
          label: "Reginald Thelonious Worthington III Dies",
          tint: "war",
          obs: "Events/NewEvent",
        },
      ],
    },
    {
      id: "section3",
      label: "Endmyre Dynasty",
      items: [
        {
          type: "span",
          start: 980,
          end: 1204,
          label: "Valdris Empire",
          tint: "faculty",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1176,
          end: 1204,
          label: "Emperor Valdris IX",
          tint: "political",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1139,
          end: 1176,
          label: "Emperor Valdris VIII",
          tint: "political",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1127,
          end: 1139,
          label: "Emperor Valdris VII",
          tint: "political",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1096,
          end: 1127,
          label: "Emperor Valdris VI",
          tint: "political",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1069,
          end: 1096,
          label: "Emperor Valdris V",
          tint: "political",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1051,
          end: 1069,
          label: "Emperor Valdris IV",
          tint: "political",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1021,
          end: 1051,
          label: "Emperor Valdris III",
          tint: "political",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 993,
          end: 1021,
          label: "Emperor Valdris II",
          tint: "political",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 980,
          end: 993,
          label: "Emperor Valdris The Great",
          tint: "political",
          obs: "Events/NewEvent",
        },
      ],
    },
    {
      id: "section4",
      label: "Priestess Line",
      items: [
        {
          type: "span",
          start: 1124,
          end: 1144,
          label: "High Priestess Eira Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1144,
          end: 1164,
          label: "High Priestess Kara Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1164,
          end: 1184,
          label: "High Priestess Ilonna Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1184,
          end: 1202,
          label: "High Priestess Maret Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1202,
          end: 1240,
          label: "High Priestess ???",
          tint: "war",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1104,
          end: 1124,
          label: "High Priestess Maisy Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1084,
          end: 1104,
          label: "High Priestes Rubia Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1064,
          end: 1084,
          label: "High Priestess Ida Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1044,
          end: 1064,
          label: "High Priestess Petra Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1024,
          end: 1044,
          label: "High Priestess Lena Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 1004,
          end: 1024,
          label: "High Priestess ???",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 984,
          end: 1004,
          label: "High Priestess Lotte Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
        {
          type: "span",
          start: 964,
          end: 984,
          label: "High Priestess Marie-Christine Aigner",
          tint: "noble",
          obs: "Events/NewEvent",
        },
      ],
    },
  ],
};
